parameters:
    bazinga.jstranslation.controller.class: 'Bazinga\Bundle\JsTranslationBundle\Controller\Controller'

services:
    bazinga.jstranslation.controller:
        class: '%bazinga.jstranslation.controller.class%'
        public: true
        arguments:
            - '@translator'
            - '@twig'
            - '@bazinga.jstranslation.translation_finder'
            - '%kernel.cache_dir%/bazinga-js-translation'
            - '%kernel.debug%'
            - ~  # fallback (locale)
            - ~  # default domain
            - ~  # http cache time